site_name: University College Pedro Society
site_url: https://univox-students.github.io/Pedro
base_url: https://univox-students.github.io/Pedro

repo_url: https://github.com/univox-students/Pedro
repo_name: univox-students/Pedro

site_description: The Univ PedroSoc is a series of student-led talks that aim to showcase mathematics and computer science that lies outside a typical undergraduate course.
site_author: Pedro Society committees.

copyright: Copyright &copy; 2024 Pedro Society, University College, Oxford. Website made by Samuel Chun Hei Lam.

nav:
  - Home: index.md
  - Previous Talks:
    - 2025-2026: prev_talks/2526.md
    - 2024-2025: prev_talks/2425.md
    - 2023-2024: prev_talks/2324.md
  - Governance: governance.md
  - Giving a Talk: giving_a_talk.md


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.tracking